version: "3"

services:
  # aws_sync:
  #   build: ./aws_sync
  #   container_name: aws_sync
  #   volumes:
  #     - sensordata:/app/data
  #   env_file:
  #     - .env
  #   network_mode: host

  sensor:
    build: ./sensor_server
    container_name: sensor_server
    volumes:
      - sensordata:/app/data/
    env_file:
      - .env
    restart: on-failure
    network_mode: host

  nginx:
    build: ./nginx
    container_name: nginx
    env_file:
      - .env
    restart: always
    network_mode: host

volumes:
  sensordata:
    driver: local
